server:
  port: 8080
  servlet:
    context-path: /learnpoem
  cors:
    allowed-origins: "http://localhost:5173" # 允许的源
    allowed-methods: GET, POST, PUT, DELETE, OPTIONS # 允许的方法
    allowed-headers: "*" # 允许的头
    allow-credentials: true # 是否允许凭证
    max-age: 3600 # 预检请求的缓存时间（秒）

spring:
  web:
    resources:
      static-locations: classpath:/staticResources
  MVC:
    format:
      date: yyyy-MM-dd HH:mm:ss